import { createPortal } from "react-dom";

/**
 * Pointer-tracked drag-and-drop for INTERNAL chrome interactions (tab →
 * split drop, sidebar worktree reorder).
 *
 * Deliberately NOT HTML5 drag-and-drop: the Tauri window keeps native
 * drag-drop interception enabled (`dragDropEnabled` default) because the
 * terminal and file tree consume real file drops via `onDragDropEvent` —
 * and with that interception on, WKWebView delivers DOM `dragover` but
 * swallows the DOM `drop`/`dragend`, so an HTML5 drop target highlights
 * and then never fires. WebKit additionally refuses to start element
 * drags from `<button>`s (the sidebar rows). Tracking mousemove/mouseup
 * ourselves sidesteps the whole native drag session.
 *
 * Call from a mousedown handler. Nothing happens until the pointer
 * travels past a small threshold — a plain click never triggers
 * `onStart`. Once dragging:
 *
 *   - text selection + cursor are locked for the duration
 *   - `onMove` fires per mousemove (use for ghost position + hit-tests)
 *   - mouseup fires `onDrop(x, y)` then `onEnd`; Escape cancels with
 *     `onEnd` only
 *   - the click event generated by the ending mouseup is swallowed
 *     (capture-phase, one-shot) so the drop doesn't ALSO activate
 *     whatever the drag started on
 */
/** True while any pointer drag is past its threshold. Unlike a native
 *  drag session, pointer tracking doesn't suppress mouseenter/hover on
 *  the elements swept over — hover-intent UI (worktree hover cards,
 *  tab tooltips) checks this to stay closed mid-drag. */
let dragActive = false;
export function pointerDragActive(): boolean {
  return dragActive;
}

export function beginPointerDrag(
  down: { button: number; clientX: number; clientY: number },
  h: {
    onStart?: (x: number, y: number) => void;
    onMove?: (x: number, y: number) => void;
    onDrop?: (x: number, y: number) => void;
    /** Always fires last, drag or plain click. */
    onEnd?: () => void;
  },
): void {
  if (down.button !== 0) return;
  const THRESHOLD_PX = 5;
  const sx = down.clientX;
  const sy = down.clientY;
  let started = false;

  const onMove = (e: MouseEvent) => {
    if (!started) {
      if (
        Math.abs(e.clientX - sx) + Math.abs(e.clientY - sy) <
        THRESHOLD_PX
      ) {
        return;
      }
      started = true;
      dragActive = true;
      document.body.style.userSelect = "none";
      document.body.style.cursor = "grabbing";
      h.onStart?.(e.clientX, e.clientY);
    }
    h.onMove?.(e.clientX, e.clientY);
  };

  const finish = (drop: MouseEvent | null) => {
    window.removeEventListener("mousemove", onMove, true);
    window.removeEventListener("mouseup", onUp, true);
    window.removeEventListener("keydown", onKey, true);
    if (started) {
      dragActive = false;
      document.body.style.userSelect = "";
      document.body.style.cursor = "";
      // Swallow the click this mouseup is about to generate — without
      // this, dropping a tab onto the view ALSO "clicks" the tab (or
      // row) the drag started from.
      const swallow = (ce: MouseEvent) => {
        ce.stopPropagation();
        ce.preventDefault();
      };
      window.addEventListener("click", swallow, { capture: true, once: true });
      setTimeout(
        () => window.removeEventListener("click", swallow, true),
        0,
      );
      if (drop) h.onDrop?.(drop.clientX, drop.clientY);
    }
    h.onEnd?.();
  };

  const onUp = (e: MouseEvent) => finish(e);
  const onKey = (e: KeyboardEvent) => {
    if (e.key === "Escape") finish(null);
  };

  // Capture phase: terminal panes / editors can't stopPropagation the
  // drag out from under us.
  window.addEventListener("mousemove", onMove, true);
  window.addEventListener("mouseup", onUp, true);
  window.addEventListener("keydown", onKey, true);
}

/**
 * Floating label that trails the pointer during a pointer drag. Offset
 * from the cursor so `document.elementFromPoint(x, y)` hit-tests (used
 * by drop targets) never land on the ghost itself; `pointerEvents:
 * none` guards the same for the offset region.
 */
export function DragGhost({
  x,
  y,
  label,
}: {
  x: number;
  y: number;
  label: string;
}) {
  return createPortal(
    <div
      aria-hidden
      style={{
        position: "fixed",
        left: x + 14,
        top: y + 10,
        zIndex: 2000,
        pointerEvents: "none",
        padding: "3px 10px",
        borderRadius: "var(--radius-sm)",
        backgroundColor: "var(--surface-3)",
        border: "1px solid var(--border-strong)",
        color: "var(--text-primary)",
        fontSize: "var(--text-xs)",
        fontFamily: "var(--font-sans)",
        boxShadow: "0 4px 12px oklch(0% 0 0 / 0.4)",
        maxWidth: 240,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
      }}
    >
      {label}
    </div>,
    document.body,
  );
}
