import type { ComponentType } from "react";
import {
  AnchorIcon,
  ArrowsOutCardinalIcon,
  AtomIcon,
  BabyIcon,
  BalloonIcon,
  BankIcon,
  BasketIcon,
  BooksIcon,
  BrainIcon,
  BugIcon,
  CarrotIcon,
  CircleIcon,
  ClockIcon,
  CloudIcon,
  CodeIcon,
  CoffeeBeanIcon,
  CoffeeIcon,
  CompassIcon,
  CookieIcon,
  CrownIcon,
  CubeIcon,
  CurrencyCircleDollarIcon,
  DatabaseIcon,
  DesktopIcon,
  DetectiveIcon,
  DiamondIcon,
  DnaIcon,
  DownloadSimpleIcon,
  DropIcon,
  EnvelopeIcon,
  FadersIcon,
  FireIcon,
  FirstAidKitIcon,
  FlagIcon,
  FlowerIcon,
  FolderIcon,
  FoldersIcon,
  FolderSimpleUserIcon,
  ForkKnifeIcon,
  GameControllerIcon,
  GearSixIcon,
  GithubLogoIcon,
  GlobeHemisphereWestIcon,
  GlobeIcon,
  GraduationCapIcon,
  HeadphonesIcon,
  HeartIcon,
  HexagonIcon,
  HouseIcon,
  ImageIcon,
  KeyIcon,
  KnifeIcon,
  LaptopIcon,
  LeafIcon,
  LightbulbIcon,
  LightningIcon,
  LinkIcon,
  MagnifyingGlassIcon,
  MagnifyingGlassPlusIcon,
  MegaphoneIcon,
  MicroscopeIcon,
  MoonIcon,
  MountainsIcon,
  MusicNoteIcon,
  MusicNotesIcon,
  NoteIcon,
  NotebookIcon,
  NotePencilIcon,
  OctagonIcon,
  OrangeIcon,
  PackageIcon,
  PaintBrushIcon,
  PaintBucketIcon,
  PaletteIcon,
  PenNibIcon,
  PencilIcon,
  PercentIcon,
  PersonSimpleTaiChiIcon,
  PhoneIcon,
  PillIcon,
  PizzaIcon,
  PlusIcon,
  PulseIcon,
  PuzzlePieceIcon,
  RocketIcon,
  RssIcon,
  ScissorsIcon,
  ShieldIcon,
  ShoppingCartIcon,
  SkullIcon,
  SmileyIcon,
  SnowflakeIcon,
  StarIcon,
  StethoscopeIcon,
  StrategyIcon,
  SunIcon,
  TShirtIcon,
  TargetIcon,
  TaxiIcon,
  TeaBagIcon,
  TerminalWindowIcon,
  TestTubeIcon,
  ToolboxIcon,
  TornadoIcon,
  TractorIcon,
  TrafficSignalIcon,
  TrainIcon,
  TrayIcon,
  TreeIcon,
  TreeStructureIcon,
  TriangleIcon,
  TruckIcon,
  UmbrellaIcon,
  UsbIcon,
  UserIcon,
  VolleyballIcon,
  WalletIcon,
  WifiHighIcon,
  WindowsLogoIcon,
  WrenchIcon,
} from "@phosphor-icons/react";

export interface PickerIcon {
  /** Stable identifier — stored on Project / Worktree as iconName. */
  name: string;
  /** Search keywords (lowercased). */
  label: string;
  Component: ComponentType<{ size?: number }>;
}

/**
 * Curated set for the icon picker dialog. Stable string keys so saved
 * state survives library version bumps; if a stored name isn't in the
 * registry, lookups fall back to the project's glyph cleanly via
 * `lookupPickerIcon`. Glyphs render via Phosphor Icons; the `name`
 * keys are intentionally kept stable across the hugeicons→Phosphor
 * migration so existing saved icons keep resolving.
 */
export const PICKER_ICONS: PickerIcon[] = [
  { name: "Folder01", label: "folder", Component: FolderIcon },
  { name: "Folder02", label: "folder file", Component: FoldersIcon },
  { name: "Folder03", label: "folder shared", Component: FolderSimpleUserIcon },
  { name: "House01", label: "home house", Component: HouseIcon },
  { name: "Library", label: "library books", Component: BooksIcon },
  { name: "University", label: "university school college", Component: BankIcon },

  { name: "Note", label: "note paper text", Component: NoteIcon },
  { name: "Notebook01", label: "notebook journal", Component: NotebookIcon },
  { name: "FileEdit", label: "file edit document", Component: NotePencilIcon },
  { name: "Image01", label: "image picture photo", Component: ImageIcon },
  { name: "Mp301", label: "music audio mp3", Component: MusicNotesIcon },
  { name: "MusicNote01", label: "music note song", Component: MusicNoteIcon },
  { name: "Headphones", label: "headphones audio", Component: HeadphonesIcon },

  { name: "Code", label: "code programming source", Component: CodeIcon },
  { name: "ComputerTerminal01", label: "terminal shell command", Component: TerminalWindowIcon },
  { name: "Computer", label: "computer pc desktop", Component: DesktopIcon },
  { name: "Laptop", label: "laptop computer", Component: LaptopIcon },
  { name: "Database01", label: "database storage data", Component: DatabaseIcon },
  { name: "Cloud", label: "cloud storage", Component: CloudIcon },
  { name: "Cube", label: "cube package box", Component: CubeIcon },
  { name: "Package", label: "package delivery", Component: PackageIcon },
  { name: "Github", label: "github git repository", Component: GithubLogoIcon },
  { name: "Office365", label: "office microsoft", Component: WindowsLogoIcon },
  { name: "Usb", label: "usb cable", Component: UsbIcon },
  { name: "Wifi01", label: "wifi internet wireless", Component: WifiHighIcon },

  { name: "Brain", label: "brain mind ai", Component: BrainIcon },
  { name: "Atom01", label: "atom science chemistry", Component: AtomIcon },
  { name: "Dna01", label: "dna biology genetics", Component: DnaIcon },
  { name: "TestTube01", label: "test tube experiment science", Component: TestTubeIcon },
  { name: "Microscope", label: "microscope research science", Component: MicroscopeIcon },
  { name: "Pulse01", label: "pulse health activity", Component: PulseIcon },
  { name: "Stethoscope02", label: "stethoscope medical health", Component: StethoscopeIcon },
  { name: "Doctor01", label: "doctor medical hospital", Component: FirstAidKitIcon },

  { name: "Wallet01", label: "wallet cash money", Component: WalletIcon },
  { name: "ShoppingCart01", label: "shopping cart store", Component: ShoppingCartIcon },
  { name: "ShoppingBasket01", label: "shopping basket store", Component: BasketIcon },
  { name: "DollarCircle", label: "dollar money currency", Component: CurrencyCircleDollarIcon },
  { name: "Percent", label: "percent percentage", Component: PercentIcon },
  { name: "Crown02", label: "crown royalty premium", Component: CrownIcon },
  { name: "Diamond01", label: "diamond gem premium", Component: DiamondIcon },

  { name: "Pizza01", label: "pizza food", Component: PizzaIcon },
  { name: "Coffee01", label: "coffee cup drink", Component: CoffeeIcon },
  { name: "CoffeeBeans", label: "coffee beans", Component: CoffeeBeanIcon },
  { name: "Tea", label: "tea drink", Component: TeaBagIcon },
  { name: "Cafe", label: "cafe coffee", Component: CoffeeIcon },
  { name: "Cookie", label: "cookie food", Component: CookieIcon },
  { name: "Steak", label: "steak meat food", Component: ForkKnifeIcon },
  { name: "Knife01", label: "knife kitchen", Component: KnifeIcon },
  { name: "Watermelon", label: "watermelon fruit", Component: OrangeIcon },
  { name: "VegetarianFood", label: "vegetarian veggie food", Component: CarrotIcon },

  { name: "Tree01", label: "tree nature forest", Component: TreeIcon },
  { name: "Leaf01", label: "leaf nature plant", Component: LeafIcon },
  { name: "Flower", label: "flower nature", Component: FlowerIcon },
  { name: "Mountain", label: "mountain nature peak", Component: MountainsIcon },

  { name: "Sun01", label: "sun day weather", Component: SunIcon },
  { name: "Moon", label: "moon night", Component: MoonIcon },
  { name: "Snow", label: "snow winter", Component: SnowflakeIcon },
  { name: "Fire", label: "fire flame hot", Component: FireIcon },
  { name: "Droplet", label: "droplet water", Component: DropIcon },
  { name: "Tornado01", label: "tornado weather storm", Component: TornadoIcon },
  { name: "Earth", label: "earth globe world", Component: GlobeIcon },
  { name: "Globe02", label: "globe world internet", Component: GlobeHemisphereWestIcon },

  { name: "Truck", label: "truck transport delivery", Component: TruckIcon },
  { name: "Train01", label: "train transport", Component: TrainIcon },
  { name: "Taxi", label: "taxi cab transport", Component: TaxiIcon },
  { name: "Rocket01", label: "rocket launch space", Component: RocketIcon },
  { name: "Tractor", label: "tractor farm vehicle", Component: TractorIcon },
  { name: "TrafficLight", label: "traffic light signal", Component: TrafficSignalIcon },
  { name: "HotAirBalloon", label: "hot air balloon flight", Component: BalloonIcon },

  { name: "User", label: "user person profile", Component: UserIcon },
  { name: "Kid", label: "kid child", Component: BabyIcon },
  { name: "Game", label: "game gaming", Component: GameControllerIcon },
  { name: "Volleyball", label: "volleyball sport", Component: VolleyballIcon },
  { name: "Yoga01", label: "yoga meditation", Component: PersonSimpleTaiChiIcon },
  { name: "Strategy", label: "strategy plan", Component: StrategyIcon },
  { name: "Puzzle", label: "puzzle solve game", Component: PuzzlePieceIcon },

  { name: "Favourite", label: "favourite favorite love heart", Component: HeartIcon },
  { name: "Smile", label: "smile happy emoji", Component: SmileyIcon },
  { name: "Star", label: "star favorite", Component: StarIcon },
  { name: "Skull", label: "skull dark", Component: SkullIcon },
  { name: "Mask", label: "mask incognito anonymous", Component: DetectiveIcon },
  { name: "Shirt01", label: "shirt clothing", Component: TShirtIcon },
  { name: "Mortarboard01", label: "graduation cap school", Component: GraduationCapIcon },

  { name: "Clock01", label: "clock time", Component: ClockIcon },
  { name: "Mail01", label: "mail email letter", Component: EnvelopeIcon },
  { name: "Inbox", label: "inbox mail incoming", Component: TrayIcon },
  { name: "Telephone", label: "telephone phone call", Component: PhoneIcon },
  { name: "Megaphone01", label: "megaphone announcement", Component: MegaphoneIcon },
  { name: "Rss", label: "rss feed news", Component: RssIcon },

  { name: "Search01", label: "search find", Component: MagnifyingGlassIcon },
  { name: "Zoom", label: "zoom magnify", Component: MagnifyingGlassPlusIcon },
  { name: "Compass", label: "compass navigation direction", Component: CompassIcon },
  { name: "Target01", label: "target goal aim", Component: TargetIcon },
  { name: "AnchorPoint", label: "anchor pin", Component: AnchorIcon },

  { name: "Tools", label: "tools utility wrench", Component: ToolboxIcon },
  { name: "Wrench01", label: "wrench fix tool", Component: WrenchIcon },
  { name: "Scissor01", label: "scissors cut", Component: ScissorsIcon },
  { name: "PenTool01", label: "pen tool design", Component: PenNibIcon },
  { name: "Pencil", label: "pencil edit write", Component: PencilIcon },
  { name: "PaintBoard", label: "paint board art", Component: PaletteIcon },
  { name: "PaintBrush01", label: "paint brush art", Component: PaintBrushIcon },
  { name: "PaintBucket", label: "paint bucket fill", Component: PaintBucketIcon },

  { name: "Key01", label: "key access password", Component: KeyIcon },
  { name: "Shield01", label: "shield security protect", Component: ShieldIcon },

  { name: "Flag01", label: "flag mark", Component: FlagIcon },
  { name: "Bug02", label: "bug debug issue", Component: BugIcon },
  { name: "Flash", label: "flash speed lightning", Component: LightningIcon },
  { name: "Zap", label: "zap lightning electric", Component: LightningIcon },
  { name: "Umbrella", label: "umbrella rain weather", Component: UmbrellaIcon },
  { name: "Lamp01", label: "lamp light idea", Component: LightbulbIcon },
  { name: "Mixer", label: "mixer audio", Component: FadersIcon },
  { name: "Move", label: "move resize", Component: ArrowsOutCardinalIcon },
  { name: "WorkflowSquare01", label: "workflow process", Component: TreeStructureIcon },
  { name: "Link01", label: "link chain url", Component: LinkIcon },
  { name: "Download01", label: "download save", Component: DownloadSimpleIcon },
  { name: "Add01", label: "add plus", Component: PlusIcon },
  { name: "Hexagon", label: "hexagon shape", Component: HexagonIcon },
  { name: "Octagon", label: "octagon shape", Component: OctagonIcon },
  { name: "Triangle01", label: "triangle shape", Component: TriangleIcon },
  { name: "Circle", label: "circle shape", Component: CircleIcon },
  { name: "Oval", label: "oval shape", Component: PillIcon },
  { name: "Gears", label: "gear settings cog", Component: GearSixIcon },
];

const PICKER_REGISTRY = new Map<string, PickerIcon>(
  PICKER_ICONS.map((p) => [p.name, p]),
);

export function lookupPickerIcon(name: string | undefined | null): PickerIcon | null {
  if (!name) return null;
  return PICKER_REGISTRY.get(name) ?? null;
}
